### ISSUE TITLE
3.x版本支援問題？

### ISSUE THREAD

**Issue by iyotetsuya** [visioncan/hexo-tag-flickr#2]
安裝後執行hexo g後出現：
ERROR Plugin load failed: hexo-tag-flickr
ReferenceError: hexo is not defined

請問是目前沒有支援新版本嗎？
hexo: 3.1.1

**Comment by visioncan** [comment]
已支援，之前沒 push 上來，現已 push 囉!

**Comment by iyotetsuya** [comment]
執行過程出現
Error: Cannot find module 'hexo-util'
安裝npm install hexo-util --save後已解

**Comment by visioncan** [comment]
應該是我 hexo blog 目錄有裝 hexo-util 所以沒有出現此問題，謝謝告知! :smile:
