### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by gleb-svechnikov** [visioncan/hexo-tag-flickr#3]
I've added following code to _config.yml 
```
plugins:
  - hexo-tag-flickr
flickr_api_key: c8cefd042deb1c96d119c1754ec8525d
```
and another peace of code to post md file
```
date: 2014-05-18 17:20:34
photos:
  - flickr 22296133211 m
---
```
However  if I use general way to add image it works fine
```
![https://farm1.staticflickr.com/622/22097018840_d9c9d5b1d9_h.jpg](https://farm1.staticflickr.com/622/22097018840_d9c9d5b1d9_h.jpg)
```
Is there any way to check whether plugin works or not? May be some log file?

**Comment by visioncan** [comment]
I test  on Hexo v3.+ , and hexo-tag-flickr v0.3.1. 
What is your version and error log? thx.

**Comment by gleb-svechnikov** [comment]
Hexo v3.1.1, hexo-tag-flickr v0.3.1. I don't get any error in console log from hexo it's just doesn't render image.

**Comment by visioncan** [comment]
<img width="867" alt="shot 2015-10-27 4 27 36" src="https://cloud.githubusercontent.com/assets/314373/10752984/ab272ebe-7cc8-11e5-81a6-e06ac649dbad.png">
Tested work. Maybe theme issue?

**Comment by gleb-svechnikov** [comment]
May be, I'll check with default theme

**Comment by visioncan** [comment]
ok! :blush:

**Comment by gleb-svechnikov** [comment]
Yes plugin did not work with hexo-theme-hueman. Thank you for fast reply.
